<?php
set_time_limit(30); date_default_timezone_set('Asia/Dhaka'); require_once __DIR__.'/../../services/OltService.php';
$pdo=oltDb(); $view=$_GET['view']??'map'; $allowed=['map','traffic','usage','devices','alerts']; if(!in_array($view,$allowed,true))$view='map';
$olts=$pdo?oltGetActiveDevices():[]; $oltStats=[]; $topology=[]; $alerts=[];
if($pdo){
$q=$pdo->query("SELECT o.id,o.device_name,o.ip_address,o.snmp_port,COALESCE(u.onu_count,0) onu_count,COALESCE(u.rx_count,0) rx_count,COALESCE(u.tx_count,0) tx_count,COALESCE(u.download_bytes,0) download_bytes,COALESCE(u.upload_bytes,0) upload_bytes,u.last_updated FROM tbl_olt_devices o LEFT JOIN (SELECT olt_ip,COUNT(*) onu_count,SUM(rx_power IS NOT NULL AND rx_power <> '') rx_count,SUM(tx_power IS NOT NULL AND tx_power <> '') tx_count,SUM(download_bytes) download_bytes,SUM(upload_bytes) upload_bytes,MAX(last_updated) last_updated FROM onu_status GROUP BY olt_ip) u ON CONVERT(u.olt_ip USING utf8mb4) COLLATE utf8mb4_general_ci=CONVERT(o.ip_address USING utf8mb4) COLLATE utf8mb4_general_ci ORDER BY o.device_name"); $oltStats=$q->fetchAll(PDO::FETCH_ASSOC);
$t=$pdo->query("SELECT olt_ip,interface_name,COUNT(*) onu_count,SUM(download_bytes) download_bytes,SUM(upload_bytes) upload_bytes,AVG(rx_power) rx_power,AVG(tx_power) tx_power,MAX(last_updated) last_updated FROM onu_status GROUP BY olt_ip,interface_name ORDER BY olt_ip,interface_name"); $topology=$t->fetchAll(PDO::FETCH_ASSOC);
foreach($oltStats as $s){if(!(int)$s['onu_count'])$alerts[]=['danger','OLT has no collected ONU data',$s['device_name']];if($s['last_updated']&&strtotime($s['last_updated'])<time()-900)$alerts[]=['warning','ONU data is older than 15 minutes',$s['device_name']];}
try{$low=$pdo->query("SELECT interface_name,olt_ip,rx_power FROM onu_status WHERE rx_power IS NOT NULL AND rx_power < -30 ORDER BY rx_power LIMIT 20")->fetchAll(PDO::FETCH_ASSOC);foreach($low as $r)$alerts[]=['danger','Low RX power: '.$r['rx_power'].' dBm',$r['olt_ip'].' / '.$r['interface_name']];}catch(Throwable $e){}}
$totalOnu=array_sum(array_column($oltStats,'onu_count')); $totalRx=array_sum(array_column($oltStats,'rx_count')); $totalTx=array_sum(array_column($oltStats,'tx_count')); $totalDown=0; foreach($oltStats as $s)if(!(int)$s['onu_count'])$totalDown++;
function gb($v){return round((float)$v/1073741824,2);} $topologyJson=json_encode($topology,JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_AMP|JSON_HEX_QUOT); $rootName=json_encode($oltStats[0]['device_name']??'OLT',JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_AMP|JSON_HEX_QUOT);
?>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><style>
.nm-wrap{padding:18px}.nm-nav{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:16px}.nm-nav a{padding:9px 14px;border-radius:9px;text-decoration:none;background:#f1f5f9;color:#334155;font-weight:600}.nm-nav a.active{background:#2563eb;color:#fff}.nm-kpis{display:grid;grid-template-columns:repeat(5,minmax(120px,1fr));gap:12px;margin-bottom:16px}.nm-card{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:14px;box-shadow:0 2px 8px rgba(15,23,42,.05)}.nm-kpi{font-size:24px;font-weight:700}.nm-muted{color:#64748b;font-size:12px}.nm-grid{display:grid;grid-template-columns:2fr 1fr;gap:16px}.nm-table{width:100%;border-collapse:collapse}.nm-table th,.nm-table td{padding:10px;border-bottom:1px solid #e5e7eb;text-align:left}.nm-table th{font-size:12px;color:#64748b}.nm-status{display:inline-block;padding:4px 8px;border-radius:999px;color:#fff;font-size:11px}.nm-alert{padding:10px;border-radius:8px;margin-bottom:8px;background:#fff7ed}.nm-map{height:560px;border-radius:12px;overflow:hidden}.nm-bar{height:8px;background:#e2e8f0;border-radius:10px;overflow:hidden}.nm-bar span{display:block;height:100%;background:#2563eb}.nm-big{font-size:34px;font-weight:800}.nm-legend{position:absolute;z-index:900;background:#fff;padding:8px 10px;border-radius:8px;box-shadow:0 2px 8px #0002;font-size:12px;margin:10px}.nm-node{font-weight:700}.nm-info{padding:8px}.nm-warning{margin-top:10px;padding:8px 10px;border-radius:8px;background:#fff7ed;color:#9a3412;font-size:12px}@media(max-width:900px){.nm-kpis{grid-template-columns:repeat(2,1fr)}.nm-grid{grid-template-columns:1fr}}
</style>
<div class="nm-wrap"><div class="d-flex justify-content-between align-items-center mb-2"><div><h4 class="mb-1">Network Monitoring</h4><div class="nm-muted">Logical OLT → interface → ONU topology and network health</div></div><button class="btn btn-sm btn-outline-primary" onclick="location.reload()">↻ Refresh</button></div>
<div class="nm-nav"><a class="<?=$view==='map'?'active':''?>" href="?page=network_monitoring&view=map">▦ Network Map</a><a class="<?=$view==='traffic'?'active':''?>" href="?page=network_monitoring&view=traffic">⌁ Traffic Monitor</a><a class="<?=$view==='usage'?'active':''?>" href="?page=network_monitoring&view=usage">▥ High Usage</a><a class="<?=$view==='devices'?'active':''?>" href="?page=network_monitoring&view=devices">◉ Device Watcher</a><a class="<?=$view==='alerts'?'active':''?>" href="?page=network_monitoring&view=alerts">⚠ Logs & Alerts</a></div>
<div class="nm-kpis"><div class="nm-card"><div class="nm-muted">OLT Devices</div><div class="nm-kpi"><?=count($olts)?></div></div><div class="nm-card"><div class="nm-muted">ONUs</div><div class="nm-kpi"><?=$totalOnu?></div></div><div class="nm-card"><div class="nm-muted">RX Data Cells</div><div class="nm-kpi"><?=$totalRx?></div></div><div class="nm-card"><div class="nm-muted">TX Data Cells</div><div class="nm-kpi"><?=$totalTx?></div></div><div class="nm-card"><div class="nm-muted">OLT With No ONU Data</div><div class="nm-kpi"><?=$totalDown?></div></div></div>
<?php if($view==='map'): ?><div class="nm-grid"><div class="nm-card"><div id="nmMap" class="nm-map"></div><div class="nm-warning">Logical topology view: interface/ONU positions are derived from monitoring relationships. GPS coordinates are not stored yet, so this map does not claim physical locations.</div></div><div class="nm-card"><h6>Network Nodes</h6><?php foreach($oltStats as $s): ?><div class="d-flex justify-content-between align-items-center py-2 border-bottom"><div><strong><?=htmlspecialchars($s['device_name'])?></strong><div class="nm-muted"><?=htmlspecialchars($s['ip_address'])?>:<?=intval($s['snmp_port'])?></div></div><span class="nm-status <?=$s['onu_count']?'bg-success':'bg-danger'?>"><?=intval($s['onu_count'])?> ONUs</span></div><?php endforeach;?><hr><div class="nm-muted">Interface clusters: <?=count($topology)?></div></div></div>
<?php elseif($view==='traffic'): ?><div class="nm-grid"><div class="nm-card"><h6>OLT Traffic</h6><table class="nm-table"><thead><tr><th>Device</th><th>Download</th><th>Upload</th></tr></thead><tbody><?php foreach($oltStats as $s): ?><tr><td><?=htmlspecialchars($s['device_name'])?></td><td><?=gb($s['download_bytes'])?> GB</td><td><?=gb($s['upload_bytes'])?> GB</td></tr><?php endforeach;?></tbody></table></div><div class="nm-card"><div class="nm-muted">Total Download</div><div class="nm-big"><?=gb(array_sum(array_column($oltStats,'download_bytes')))?></div><hr><div class="nm-muted">Total Upload</div><div class="nm-big"><?=gb(array_sum(array_column($oltStats,'upload_bytes')))?></div></div></div>
<?php elseif($view==='usage'): ?><div class="nm-card"><h6>High Usage Monitor</h6><?php $rows=[];if($pdo){try{$rows=$pdo->query("SELECT olt_ip,interface_name,serial,COALESCE(download_bytes,0)+COALESCE(upload_bytes,0) total_bytes FROM onu_status ORDER BY total_bytes DESC LIMIT 20")->fetchAll(PDO::FETCH_ASSOC);}catch(Throwable $e){}}$max=$rows?max(array_column($rows,'total_bytes')):1; ?><table class="nm-table"><thead><tr><th>OLT</th><th>Interface</th><th>Serial</th><th>Usage</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?=htmlspecialchars($r['olt_ip'])?></td><td><?=htmlspecialchars($r['interface_name'])?></td><td><?=htmlspecialchars($r['serial'])?></td><td><strong><?=gb($r['total_bytes'])?> GB</strong><div class="nm-bar"><span style="width:<?=min(100,((float)$r['total_bytes']/$max)*100)?>%"></span></div></td></tr><?php endforeach;?></tbody></table></div>
<?php elseif($view==='devices'): ?><div class="nm-card"><h6>Device Watcher</h6><table class="nm-table"><thead><tr><th>Device</th><th>IP</th><th>ONU Count</th><th>Last Data</th><th>Status</th></tr></thead><tbody><?php foreach($oltStats as $s):$fresh=$s['last_updated']&&strtotime($s['last_updated'])>=time()-900&&(int)$s['onu_count']>0; ?><tr><td><?=htmlspecialchars($s['device_name'])?></td><td><?=htmlspecialchars($s['ip_address'])?></td><td><?=intval($s['onu_count'])?></td><td><?=htmlspecialchars($s['last_updated']??'-')?></td><td><span class="nm-status <?=$fresh?'bg-success':'bg-danger'?>"><?=$fresh?'ONLINE':'WATCH'?></span></td></tr><?php endforeach;?></tbody></table></div>
<?php else: ?><div class="nm-card"><h6>Logs & Alerts</h6><?php if(!$alerts): ?><div class="alert alert-success">No active monitoring alerts detected.</div><?php else:foreach($alerts as $a): ?><div class="nm-alert"><strong><?=htmlspecialchars($a[1])?></strong><div class="nm-muted"><?=htmlspecialchars($a[2])?></div></div><?php endforeach;endif;?></div><?php endif; ?></div>
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>document.addEventListener('DOMContentLoaded',function(){var e=document.getElementById('nmMap');if(!e||typeof L==='undefined')return;var rows=<?=$topologyJson?:'[]'?>,m=L.map('nmMap').setView([23.8103,90.4125],11);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(m);var olt=<?=$rootName?>;var center=[23.8103,90.4125],root=L.circleMarker(center,{radius:14,color:'#2563eb',fillColor:'#2563eb',fillOpacity:.9}).addTo(m).bindPopup('<div class="nm-info"><div class="nm-node">'+olt+'</div><div>OLT root</div></div>');var n=Math.max(rows.length,1),bounds=[center];rows.forEach(function(r,i){var a=(Math.PI*2*i/n)-Math.PI/2,d=0.025+Math.min(0.02,i/Math.max(n,1)*0.015),p=[center[0]+Math.sin(a)*d,center[1]+Math.cos(a)*d];var c=L.circleMarker(p,{radius:Math.min(14,7+Math.log10(Math.max(1,r.onu_count))*4),color:r.onu_count?'#16a34a':'#dc2626',fillColor:r.onu_count?'#22c55e':'#ef4444',fillOpacity:.85}).addTo(m).bindPopup('<div class="nm-info"><div class="nm-node">'+r.interface_name+'</div><div>'+r.onu_count+' ONUs</div><div>RX '+(r.rx_power===null?'-':Number(r.rx_power).toFixed(2))+' dBm</div><div>TX '+(r.tx_power===null?'-':Number(r.tx_power).toFixed(2))+' dBm</div></div>');L.polyline([center,p],{color:r.onu_count?'#16a34a':'#dc2626',weight:3,opacity:.7}).addTo(m);bounds.push(p)});if(bounds.length>1)m.fitBounds(bounds,{padding:[25,25]});});</script>
